{% set name = "nionui-tool" %}
{% set version = "0.3.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [py2k]
  entry_points:
    - nionui-tool = nion.nionui_tool.command:main

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools
  run:
    - python >=3.6

about:
  home: http://github.com/nion-software/nionui-tool
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "A native launcher for Nion UI apps."
  dev_url: https://github.com/nion-software/nionui-tool

extra:
  recipe-maintainers:
    - cmeyer
