github:
  user_or_org: nion-software
channels:
  targets:
  - [nion, main]
provider:
  linux: travis
  osx: travis
  win: appveyor
min_py_ver: '36'
max_py_ver: '38'
travis:
  secure:
    BINSTAR_TOKEN: "k8QQj7yMUZGsANoG5Me/rc0wfZeDiBOOLPgGTOgom3OVcLrljEah6s7bNPV8uknZ7vPqbk65CTVq2FC87v+K2+vrrBJWreiN8aONOmjLuSCt2nXlrib9lEOwIQizetSUblAWP1h3qx2ZZQeV4EAQPPOxxyGLZGeSzPTjAoRVl8RSSUXZqTQaadoIxkJbtdNrJ4QC9LDEMNr0/XxW/RvyVB/8n0CkbbItK7X3lMazaTjiQby7J0hTPUAZd4nK9c9LGu37Q4L5OwWv2v3VmZgIWauQSQHm2rq7IORWy3/Zr0BJTZ9IdJGLijrPnQUxRQW/7mnSQOSbXNxvZ3XrySKnpzualHsHICJGDxZXvRm7eQkzrxrr4xBPg/f9UBtA9mjpRivKpMFN6LoJ3+EDgkflSt/xwFTbqRv+gGsZF/g11LdbYWd5DAEivu8v7urLnr9TW7quD7l8f7HV6wCcjApDFDaOTQVxsZ8ZbBBVPr3LOkBLJDQfF8dZvqlHWg294Dgk9MDVyJV8/w46IDlsHTvf2XYG7bme62C6z2JEzN6fVMbrwbf1h4FuVniWOxw2VtgRWkpnbnhLTAjU3Dn2X3ibdivxhJQARqbtptaD14C72HGsMk3pWTOSoEmRDxOj8d2gQrhclWHFtNfD8XzH9CvngSuIydHAg1pVsyO7kgtkLG0="
appveyor:
  secure:
    BINSTAR_TOKEN: 2hGJzrrLwlyZMDxCdlJkXvz5ZSGTxueLow9aH5I4zB+tOeHmSZYXRpdCctnvJqHj
