github:
  user_or_org: nion-software
channels:
  targets:
  - [nion, main]
max_py_ver: '37'
travis:
  secure:
    BINSTAR_TOKEN: S0Moerv79px7+jJA4NBvOe3tNbMh0NMINsrx5VULDZl1pH9VWPY43ddjkh0Tl0Tl8RZTyy/R4KYXRHEYfBw9lDK8DrbpB6Sy+P8CK14P1hh7JTHomYFrngfTK2FHE6D80b7R1SqpuQ+m1twClUAnxzTR5JmBd0MCORZkP97DBSSHtjrWpUW2zUsFXN/VxxEkvQYEoNIiCCZz/nB2jwcj3nMgLV/aPSlvf7IyM3T0Rk9UrppBtnqJbG0emsJTIQtswugxnBcO0pYwoDToTJCk1CkPnMrN6ZN1oC3PNfI8vhwA/Q/Xj32FhjfMgD3e2tHRVJ4CK7LGX814DHONUeRZfvdKEB9zZ3WgTZnEyuZWLyZLzORoEWVJAHP8oHrhYQfv2ocjWTkzf3/tx3jG0qhH47GtbBvjHWPNcjTZXcNaiPLZp/NwsvibzgIR0K7hiFFchA4n44k6zArUdGZU7NJTN5SfRjfdN1h9JqeADkoNPAY9QTyL75zxlZq845I1jDp4x6NWNaSQwpIFZHQaiTruG9GhhmQqU7U1sbaUCaa9jhcs7wz3jaMCJBP9Ef+pcRm9TGxHms/83dwWY5a4Oq6V/siZvNc6N+wBJ3xKV7jpHIfiYxxJVoNItvaGn6F/U9X/v9MYG0MtriOA9RDMhlJRXQ7XV3sqTrZBO20gM7/cBMk=
appveyor:
  secure:
    BINSTAR_TOKEN: YCXl78g7U9HSABZ6GYD4VrBGAFA6ieBueHfEW4d70LfpTvEESM09/RDNcQ2gK6pE
